### PR TITLE
ci: Add dependabot

### PR DESCRIPTION
**Pull request by ccoVeille**

### CODE REVIEW

**Comment by raeperd** [comment]
referenced https://docs.github.com/en/code-security/dependabot/dependabot-alerts/configuring-notific
lgtm

**Comment by ccoVeille** [comment]
The link is broken, I assume it's

https://docs.github.com/en/code-security/dependabot/dependabot-alerts/configuring-notifications-for-dependabot-alerts

**Comment by raeperd** [comment]
Default value of `open-pull-requests-limit` is 5, which is kinda reasonable to me for most projects.
And also, this project starts without any dependency so 5 is kinda enough maybe.

**Comment by ccoVeille** [comment]
Oh good catch, I wrongly assumed, there were no limit when none was provided.

I should have read the documentation

**Comment by ccoVeille** [comment]
So I'm fine with the PR

**Pull request merged**
