### PR TITLE
fix: Fix content type to application/yaml

### PR DESCRIPTION
**Pull request by raeperd**
fix https://github.com/raeperd/kickstart.go/pull/25#discussion_r1875528029

cc @ccoVeille

### CODE REVIEW

**Comment by ccoVeille** [comment]
You could have pushed your commit in my branch, no?

**Comment by raeperd** [comment]
I couldn't. maybe allow edit was needed?

**Comment by ccoVeille** [comment]
I think it's a limitation of something I tried.

I moved my forks in a dedicated organization

https://github.com/ccoveille-forks

I didn't notice until yet it may have consequence when I open a PR.

Doing it from an organization and from a user might differ slightly.

If I don't grant you to push on my fork in my organization, you might not be able to do it.

I'll have to dig further.

I did all that with a script. I might have to grant the users one by one.

Which would be easy for you on this project. But it could become a nightmare on project with multiple maintainers...

I'll have to check and reconsider

**Comment by ccoVeille** [comment]
Here is my script

https://github.com/ccoVeille/github-forks-sanitizer/pull/1

**Pull request merged**
